const items = [
    {
        id: '001',
        image: '1.jpg',
        company: 'Carlton London',
        item_name: 'Rhodium-Plated CZ Floral Studs',
        original_price: 1045,
        current_price: 606,
        discount_percentage: 42,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.5,
            count: 1400,
        },
    },

    {
        id: '002',
        image: '2.jpg',
        company: 'CUKOO',
        item_name: 'Women Padded Halter Neck Swimming Dress',
        original_price: 2599,
        current_price: 1507,
        discount_percentage: 42,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.3,
            count: 24,
        },
    },
    {
        id: '003',
        image: '3.jpg',
        company: 'NUEVOSDAMAS',
        item_name: 'Women Red & White Printed A-Line Knee-Length Skirts',
        original_price: 1599,
        current_price: 495,
        discount_percentage: 69,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.1,
            count: 249,
        },
    },
    {
        id: '004',
        image: '4.jpg',
        company: 'ADIDAS',
        item_name: 'Indian Cricket ODI Jersey',
        original_price: 999,
        current_price: 999,
        discount_percentage: 0,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 5.0,
            count: 10,
        },
    },
    {
        id: '005',
        image: '5.jpg',
        company: 'Roadster',
        item_name: 'Pure Cotton T-shirt',
        original_price: 1399,
        current_price: 489,
        discount_percentage: 65,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.2,
            count: 3500,
        },
    },
    {
        id: '006',
        image: '6.jpg',
        company: 'Nike',
        item_name: 'Men ReactX Running Shoes',
        original_price: 14995,
        current_price: 14995,
        discount_percentage: 0,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 0.0,
            count: 0,
        },
    },
    {
        id: '007',
        image: '7.jpg',
        company: 'The Indian Garage Co',
        item_name: 'Men Slim Fit Regular Shorts',
        original_price: 1599,
        current_price: 639,
        discount_percentage: 60,
        rating: {
            stars: 4.2,
            count: 388,
        },
    },
    {
        id: '008',
        image: '8.jpg',
        company: 'Nivea',
        item_name: 'Men Fresh Deodrant 150ml',
        original_price: 285,
        current_price: 142,
        discount_percentage: 50,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.2,
            count: 5200,
        },
    },

    {
        id: '009',
        image: '9.jpg',
        company: 'AL karam',
        item_name: 'Women Suit',
        original_price: 15000,
        current_price: 7500,
        discount_percentage: 50,
        return_period: 14,
        delivery_date: '10 Oct 2024',
        rating: {
            stars: 4.5,
            count: 5200,
        },
    },
       {
        id: '0010',
        image: '10.jpg',
        company: 'Gul AHmad',
        item_name: 'Men Suit',
        original_price: 8000,
        current_price: 4500,
        discount_percentage: 35,
        return_period: 14,
        delivery_date: '12 Oct 2025',
        rating: {
            stars: 4.5,
            count: 520,
        },
    },
     {
        id: '0011',
        image: '11.jpg',
        company: 'Gul AHmad',
        item_name: 'Women Clothes',
        original_price: 10000,
        current_price: 5000,
        discount_percentage: 50,
        return_period: 14,
        delivery_date: '15 Nov 2025',
        rating: {
            stars: 4.2,
            count: 395,
        },
    },
         {
        id: '0012',
        image: '12.jpg',
        company: 'Gul AHmad',
        item_name: 'Men Causual',
        original_price: 10000,
        current_price: 5000,
        discount_percentage: 50,
        return_period: 14,
        delivery_date: '20 Feb 2025',
        rating: {
            stars: 4.2,
            count: 425,
        },
    },
];